import {
  v4 as uuid
} from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [{
    _id: uuid(),
    title: "Apple Series",
    deal: "Best Deals",
    price: 96000,
    category:"mobile",
    discount:2000,
    deliveryCh:100,
    ratings:5,
    inStock:true,
    fastDelivery:true,
    mobile: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/312/312/kqjtd3k0/mobile/o/4/x/c11-2021-rmx3231-realme-original-imag4j4yrdt7d9cj.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Samsung Series",
    deal: "Best Deals",
    price: "3000",
    category:"mobile",
    discount:200,
    deliveryCh:22,
    ratings:4,
    inStock:true,
    fastDelivery:true,
    android: true,
    mobile: true,
    image: 'https://rukminim2.flixcart.com/image/312/312/l0igvww0/mobile/n/h/4/-original-imagcahnwypwuaac.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Moto Series",
    deal: "Best Deals",
    price: "1000",
    category:"mobile",
    discount:50,
    deliveryCh:23,
    ratings:5,
    inStock:true,
    fastDelivery:true,
    android: true,
    mobile: true,
    image: 'https://rukminim2.flixcart.com/image/312/312/kn22m4w0/mobile/9/k/s/galaxy-f12-sm-f127glbiins-samsung-original-imagftmhhhvghq7w.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Samsung Series",
    deal: "Best Deals",
    price: "32000",
    category:"mobile",
    discount:1000,
    deliveryCh:100,
    ratings:3,
    inStock:true,
    fastDelivery:true,
    android: true,
    mobile: true,
    image: 'https://rukminim2.flixcart.com/image/312/312/l0sgyvk0/mobile/k/x/c/-original-imagcg22czc3ggvw.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Moto Series",
    deal: "Best Deals",
    price: "11000",
    category:"mobile",
    discount:500,
    deliveryCh:70,
    ratings:5,
    inStock:true,
    fastDelivery:false,
    android: true,
    mobile: true,
    image: 'https://rukminim2.flixcart.com/image/312/312/kmwcuq80/mobile/7/p/5/galaxy-m12-galaxy-m12-samsung-original-imagfzuhqtn5kpvj.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Moto Series",
    deal: "Best Deals",
    price: "12000",
    category:"mobile",
    discount:220,
    deliveryCh:100,
    ratings:2,
    inStock:true,
    fastDelivery:false,
    android: true,
    mobile: true,
    image: 'https://rukminim2.flixcart.com/image/312/312/kqqykcw0/mobile/j/5/7/galaxy-f22-sm-e225flbdins-samsung-original-imag4z99fp4qdfby.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Samsung Series",
    deal: "Best Deals",
    price: "6000",
    category:"mobile",
    discount:600,
    deliveryCh:90,
    ratings:1,
    inStock:true,
    fastDelivery:false,
    android: true,
    mobile: true,
    image: 'https://rukminim2.flixcart.com/image/312/312/l0sgyvk0/mobile/k/x/c/-original-imagcg22czc3ggvw.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Apple series",
    deal: "Best Deals",
    price: "25000",
    category:"mobile",
    discount:2000,
    deliveryCh:100,
    ratings:5,
    inStock:true,
    fastDelivery:false,
    mobile: true,
    image: 'https://rukminim2.flixcart.com/image/312/312/kmwcuq80/mobile/7/p/5/galaxy-m12-galaxy-m12-samsung-original-imagfzuhqtn5kpvj.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Moto Series",
    deal: "Best Deals",
    price: "24000",
    category:"mobile",
    discount:1500,
    deliveryCh:78,
    ratings:4,
    inStock:false,
    fastDelivery:false,
    android: true,
    mobile: true,
    image: 'https://rukminim2.flixcart.com/image/312/312/kqqykcw0/mobile/j/5/7/galaxy-f22-sm-e225flbdins-samsung-original-imag4z99fp4qdfby.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Samsung Series",
    deal: "Best Deals",
    price: "9000",
    category:"mobile",
    discount:700,
    deliveryCh:40,
    ratings:2,
    inStock:false,
    fastDelivery:false,
    android: true,
    mobile: true,
    image: 'https://rukminim2.flixcart.com/image/312/312/l0sgyvk0/mobile/k/x/c/-original-imagcg22czc3ggvw.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Moto Series",
    deal: "Best Deals",
    price: "28000",
    category:"mobile",
    discount:2000,
    deliveryCh:100,
    ratings:4,
    inStock:false,
    fastDelivery:false,
    android: true,
    mobile: true,
    image: 'https://rukminim2.flixcart.com/image/312/312/kmwcuq80/mobile/7/p/5/galaxy-m12-galaxy-m12-samsung-original-imagfzuhqtn5kpvj.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Moto Series",
    deal: "Best Deals",
    price: "1000",
    category:"mobile",
    discount:200,
    deliveryCh:100,
    ratings:1,
    inStock:false,
    fastDelivery:false,
    android: true,
    mobile: true,
    image: 'https://rukminim2.flixcart.com/image/312/312/kqqykcw0/mobile/j/5/7/galaxy-f22-sm-e225flbdins-samsung-original-imag4z99fp4qdfby.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Apple series",
    deal: "Best Deals",
    price: "8000",
    category:"mobile",
    discount:230,
    deliveryCh:70,
    ratings:2,
    inStock:false,
    fastDelivery:true,
    mobile: true,
    android: true,
    image: 'https://rukminim2.flixcart.com/image/312/312/l0igvww0/mobile/n/h/4/-original-imagcahnwypwuaac.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Frozen Bread",
    deal: "Best Deals",
    price: "100",
    category:"grocery",
    discount:10,
    deliveryCh:0,
    ratings:3,
    inStock:true,
    fastDelivery:true,
    grocery: true,
    android: false,
    image: 'https://www.refrigeratedfrozenfood.com/ext/resources/RFF/AYO-Foods/Rudis/RM-Sourdough.jpg?t=1616526838&width=900'
  },
  {
    _id: uuid(),
    title: "Sandwich Bread",
    deal: "Best Deals",
    price: "120",
    category:"grocery",
    discount:10,
    deliveryCh:5,
    ratings:4,
    inStock:true,
    fastDelivery:false,
    grocery: true,
    android: false,
    image: 'https://i5.walmartimages.com/asr/ca5bcbca-62fb-42c5-ab32-16d019390c6c.c1944c7cc4f6eeb667ed5149c7e17caf.jpeg'
  },
  {
    _id: uuid(),
    title: "Pastires",
    deal: "Best Deals",
    price: "220",
    category:"grocery",
    discount:10,
    deliveryCh:5,
    ratings:5,
    inStock:true,
    fastDelivery:true,
    grocery: true,
    android: false,
    image: 'https://www.united-food-brands.com/wp-content/uploads/2019/05/Shires_pastries-min.png'
  },{
    _id: uuid(),
    title: "Fortune Oil",
    deal: "Best Deals",
    price: "1750",
    category:"grocery",
    discount:120,
    deliveryCh:40,
    ratings:4,
    inStock:true,
    fastDelivery:true,
    grocery: true,
    android: false,
    image: 'https://m.media-amazon.com/images/I/41fAkhF7UtL.jpg'
  },{
    _id: uuid(),
    title: "Pantanjali oil",
    deal: "Best Deals",
    price: "1600",
    category:"grocery",
    discount:70,
    deliveryCh:20,
    ratings:5,
    inStock:true,
    fastDelivery:true,
    grocery: true,
    android: false,
    image: 'https://m.media-amazon.com/images/I/81t174D6pgL._SL1500_.jpg'
  },
  {
    _id: uuid(),
    title: "Good Life oil",
    deal: "Best Deals",
    price: "1250",
    category:"grocery",
    discount:60,
    deliveryCh:25,
    ratings:2,
    inStock:true,
    fastDelivery:false,
    grocery: true,
    android: false,
    image: 'https://www.jiomart.com/images/product/600x600/491472709/good-life-refined-sunflower-oil-5-l-product-images-o491472709-p491472709-0-202203170807.jpg'
  },
  {
    _id: uuid(),
    title: "Organic Maida",
    deal: "Best Deals",
    price: "76",
    category:"grocery",
    discount:10,
    deliveryCh:5,
    ratings:2,
    inStock:false,
    fastDelivery:true,
    grocery: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/280/280/kixgtjk0/flour/v/r/w/500-wheat-maida-1-maida-organic-tattva-original-imafym8cchphahk9.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Pillsbury Atta",
    deal: "Best Deals",
    price: "259",
    category:"grocery",
    discount:20,
    deliveryCh:5,
    ratings:3,
    inStock:true,
    fastDelivery:true,
    grocery: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/280/280/kohigsw0/flour/5/q/5/atta-with-multigrains-multigrain-flour-pillsbury-original-imag2xgh4gggvzx5.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Dawaat Rice",
    deal: "Best Deals",
    price: "259",
    category:"grocery",
    discount:90,
    deliveryCh:5,
    ratings:3,
    inStock:true,
    fastDelivery:false,
    grocery: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/280/280/kqzj7gw0/rice/p/l/k/white-biryani-na-basmati-rice-pouch-daawat-original-imag4vkmbfnv4azg.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "India Gate Rice",
    deal: "Best Deals",
    price: "422",
    category:"grocery",
    discount:90,
    deliveryCh:5,
    ratings:3,
    inStock:true,
    fastDelivery:true,
    grocery: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/280/280/klscivk0/rice/r/m/p/white-regular-choice-basmati-rice-vacuum-pack-india-gate-original-imagytzcjrdgk3je.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Block Tshirt",
    deal: "Best Deals",
    price: "422",
    category:"fashion",
    discount:90,
    deliveryCh:20,
    ratings:5,
    inStock:true,
    fastDelivery:true,
    fashion: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/611/733/kkfrjww0/t-shirt/h/1/t/l-t312-cgblwh-new-eyebogler-original-imafzs5hrjgzsfpr.jpeg?q=50'
  },
  {
    _id: uuid(),
    title: "Round neck Tshirt",
    deal: "Best Deals",
    price: "249",
    category:"fashion",
    discount:80,
    deliveryCh:20,
    ratings:3,
    inStock:true,
    fastDelivery:true,
    fashion: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/611/733/khmbafk0-0/t-shirt/w/j/s/xs-t322-blwh-seven-rocks-original-imafxhagtyj2xvpn.jpeg?q=50'
  },
  {
    _id: uuid(),
    title: "Coller Tshirt",
    deal: "Best Deals",
    price: "249",
    category:"fashion",
    discount:80,
    deliveryCh:20,
    ratings:3,
    inStock:true,
    fastDelivery:true,
    fashion: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/611/733/kyrlifk0/t-shirt/0/u/s/l-tdgyblhenful-d37-tripr-original-imagax9x6pkgwwg9.jpeg?q=50'
  },
  {
    _id: uuid(),
    title: "Polo Tshirt",
    deal: "Best Deals",
    price: "462",
    category:"fashion",
    discount:80,
    deliveryCh:20,
    ratings:5,
    inStock:true,
    fastDelivery:false,
    fashion: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/611/733/k0zlsi80/t-shirt/x/g/z/xl-9329653-roadster-original-imafkktusdxdm7gd.jpeg?q=50'
  },
  {
    _id: uuid(),
    title: "Casual Shirt",
    deal: "Best Deals",
    price: "266",
    category:"fashion",
    discount:60,
    deliveryCh:50,
    ratings:4,
    inStock:false,
    fastDelivery:true,
    fashion: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/611/733/kfoapow0-0/shirt/1/l/t/m-c1276-gespo-original-imafw2gqdztqdkyu.jpeg?q=50'
  },
  {
    _id: uuid(),
    title: "Neck Green Tshirt",
    deal: "Best Deals",
    price: "500",
    category:"fashion",
    discount:60,
    deliveryCh:30,
    ratings:3,
    inStock:true,
    fastDelivery:true,
    fashion: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/611/733/kgb5rbk0-0/t-shirt/w/6/n/l-ss20-sp28-scott-international-original-imafwjzdh26cvfx9.jpeg?q=50'
  },
  {
    _id: uuid(),
    title: "Neck maroon Tshirt",
    deal: "Best Deals",
    price: "500",
    category:"fashion",
    discount:60,
    deliveryCh:30,
    ratings:5,
    inStock:true,
    fastDelivery:true,
    fashion: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/611/733/kgb5rbk0-0/t-shirt/z/i/j/s-ss20-sp22-scott-international-original-imafwjzdumkk7zdu.jpeg?q=50'
  },
  {
    _id: uuid(),
    title: "Leather Shoes",
    deal: "Best Deals",
    price: "3005",
    category:"fashion",
    discount:60,
    deliveryCh:30,
    ratings:5,
    inStock:true,
    fastDelivery:true,
    fashion: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/611/733/kiqbma80-0/shoe/p/p/d/gc-1759115-39-woodland-camel-original-imafygsbu4ckhdfj.jpeg?q=50'
  },
  {
    _id: uuid(),
    title: "Men Sandal",
    deal: "Best Deals",
    price: "252",
    category:"fashion",
    discount:32,
    deliveryCh:15,
    ratings:5,
    inStock:true,
    fastDelivery:true,
    fashion: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/611/733/kuvkcy80/sandal/h/w/a/8-xxx-01-black-red-8-sfr-black-red-original-imag7wamy9ynjqef.jpeg?q=50'
  },
  {
    _id: uuid(),
    title: "Running Shoes",
    deal: "Best Deals",
    price: "350",
    category:"fashion",
    discount:32,
    deliveryCh:15,
    ratings:2,
    inStock:true,
    fastDelivery:true,
    fashion: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/611/733/kbtp0280/shoe/c/k/k/gm1251-43-good-minar-black-original-imaft34ej4zx2z63.jpeg?q=50'
  },
  {
    _id: uuid(),
    title: "Realme watch",
    deal: "Best Deals",
    price: "4562",
    category:"electronics",
    discount:300,
    deliveryCh:100,
    ratings:5,
    inStock:true,
    fastDelivery:true,
    electronics: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/150/150/ki7qw7k0/smartwatch/e/p/b/rma207-android-realme-original-imafy2fxtuzghm5m.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Gionee watch",
    deal: "Best Deals",
    price: "1762",
    category:"electronics",
    discount:300,
    deliveryCh:100,
    ratings:1,
    inStock:true,
    fastDelivery:true,
    electronics: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/150/150/k8ytaq80/smartwatch/d/g/8/gsw5-android-ios-gionee-original-imafquuuydevhjdy.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "huami watch",
    deal: "Best Deals",
    price: "200",
    category:"electronics",
    discount:60,
    deliveryCh:20,
    ratings:3,
    inStock:true,
    fastDelivery:false,
    electronics: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/150/150/mouse/b/j/g/logitech-b175-original-imaer9wataetgtxc.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Mouse",
    deal: "Best Deals",
    price: "8562",
    category:"electronics",
    discount:500,
    deliveryCh:100,
    ratings:2,
    inStock:true,
    fastDelivery:false,
    electronics: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/150/150/kjn6qvk0/smartwatch/d/s/h/1-65-a2021-android-ios-huami-original-imafz6aqjej62grc.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "boAt Airdopes ",
    deal: "Best Deals",
    price: "1249",
    category:"electronics",
    discount:100,
    deliveryCh:50,
    ratings:5,
    inStock:true,
    fastDelivery:false,
    electronics: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/612/612/ksdjma80/headphone/o/f/c/airdopes-131-airdopes-138-boat-original-imag5yz96jehyqrg.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Realme Airdopes ",
    deal: "Best Deals",
    price: "1249",
    category:"electronics",
    discount:123,
    deliveryCh:50,
    ratings:5,
    inStock:true,
    fastDelivery:false,
    electronics: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/612/612/krayqa80/headphone/x/9/r/rma2010-realme-original-imag54ey5mxggzcy.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "boAt Blutooth ",
    deal: "Best Deals",
    price: "1049",
    category:"electronics",
    discount:123,
    deliveryCh:50,
    ratings:5,
    inStock:true,
    fastDelivery:false,
    electronics: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/612/612/ksnjp8w0/headphone/e/d/l/rockerz-255f-rockerz-255-boat-original-imag66ckxprfrsz2.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "boAt Blutooth ",
    deal: "Best Deals",
    price: "1249",
    category:"electronics",
    discount:163,
    deliveryCh:50,
    ratings:5,
    inStock:true,
    fastDelivery:true,
    electronics: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/612/612/ksw4ccw0/headphone/w/g/r/rockerz-450-boat-original-imag6cqqh49wjfy5.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "JBL EarPhones",
    deal: "Best Deals",
    price: "579",
    category:"electronics",
    discount:57,
    deliveryCh:12,
    ratings:2,
    inStock:false,
    fastDelivery:true,
    electronics: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/612/612/juwzf680/headphone-refurbished/7/h/k/z-c100si-jbl-original-imaffxja5vmgwudz.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "OPPO EarPhones",
    deal: "Best Deals",
    price: "1749",
    category:"electronics",
    discount:57,
    deliveryCh:12,
    ratings:2,
    inStock:true,
    fastDelivery:true,
    electronics: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/612/612/kyuge4w0/headphone/n/k/f/-original-imagazgucguvptdf.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Bar Stool Chair",
    deal: "Best Deals",
    price: "549",
    category:"home",
    discount:55,
    deliveryCh:12,
    ratings:5,
    inStock:true,
    fastDelivery:true,
    home: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/150/150/jd4u5jk0/bar-stool-chair/y/a/s/black-semi-aniline-leather-m-351-black-da-urban-black-original-imafff4h9dsfx5hj.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Bed Side Table",
    deal: "Best Deals",
    price: "400",
    category:"home",
    discount:65,
    deliveryCh:25,
    ratings:4,
    inStock:true,
    fastDelivery:true,
    home: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/150/150/jingcy80/coffee-table/u/m/g/rosewood-sheesham-9yiyu876-sublime-arts-walnut-brown-original-imaezfkj9pjtuep3.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Recliners",
    deal: "Best Deals",
    price: "11899",
    category:"home",
    discount:1000,
    deliveryCh:200,
    ratings:5,
    inStock:true,
    fastDelivery:false,
    home: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/150/150/jmz7csw0/recliner/f/7/7/brown-pvc-24002-woodness-original-imaf9rzvrrav8phf.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Accent Chair",
    deal: "Best Deals",
    price: "3999",
    category:"home",
    discount:99,
    deliveryCh:24,
    ratings:5,
    inStock:false,
    fastDelivery:false,
    home: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/150/150/k30h8y80/living-room-chair/j/d/e/multicolor-pp-stylish-modern-furniture-patches-chair-with-original-imafm63gcaauad7u.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Home temple",
    deal: "Best Deals",
    price: "550",
    category:"home",
    discount:60,
    deliveryCh:20,
    ratings:5,
    inStock:true,
    fastDelivery:true,
    home: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/150/150/jlb6v0w0/home-temple/n/b/g/pooja-mandir-marusthalee-original-imaf8gk4jzfdhv22.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Kitchen Trolly",
    deal: "Best Deals",
    price: "249",
    category:"home",
    discount:60,
    deliveryCh:20,
    ratings:3,
    inStock:true,
    fastDelivery:true,
    home: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/150/150/jwi518w0/kitchen-trolley/7/r/y/stainless-steel-3-tier-fruits-vegetable-trolley-3d-metro-original-imafh5ytzq5qphfv.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Lunch Box",
    deal: "Best Deals",
    price: "899",
    category:"home",
    discount:60,
    deliveryCh:20,
    ratings:5,
    inStock:true,
    fastDelivery:true,
    home: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/612/612/kpvivm80/lunch-box/h/t/o/premium-lunch-box-with-bottle-black-3-stainless-steel-containers-original-imag4yhuzapzvxg3.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Lunch Box",
    deal: "Best Deals",
    price: "980",
    category:"home",
    discount:50,
    deliveryCh:30,
    ratings:5,
    inStock:true,
    fastDelivery:false,
    home: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/612/612/ktd9mkw0/lunch-box/j/j/l/1470-teso-lunch-box-with-bottle-blue-pro-oliveware-4-original-imag6qe2auyg4ntb.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Mixer",
    deal: "Best Deals",
    price: "1649",
    category:"Appliances",
    discount:50,
    deliveryCh:30,
    ratings:5,
    inStock:true,
    fastDelivery:true,
    Appliances: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/612/612/jqv8ia80/mixer-grinder-juicer/w/n/6/butterfly-arrow-original-imafcz43zxwekpzc.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Induction",
    deal: "Best Deals",
    price: "1549",
    category:"Appliances",
    discount:80,
    deliveryCh:50,
    ratings:3,
    inStock:false,
    fastDelivery:true,
    Appliances: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/612/612/kyj0vbk0/induction-cook-top/h/0/5/-original-imagaqsng6rtrkyh.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Electric kettle",
    deal: "Best Deals",
    price: "649",
    category:"Appliances",
    discount:80,
    deliveryCh:50,
    ratings:4,
    inStock:true,
    fastDelivery:false,
    Appliances: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/612/612/k47cgi80pkrrdj/electric-kettle-refurbished/4/g/z/u-aroma-skt-180-ase-1-8-singer-original-imafn8yaykfn8pnh.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Geyser",
    deal: "Best Deals",
    price: "8333",
    category:"Appliances",
    discount:70,
    deliveryCh:50,
    ratings:4,
    inStock:true,
    fastDelivery:true,
    Appliances: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/612/612/kddf6a80/water-geyser/m/3/t/instanio-prime-3000-havells-15-original-imafua9vrycxcg4h.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Heater",
    deal: "Best Deals",
    price: "641",
    category:"Appliances",
    discount:70,
    deliveryCh:50,
    ratings:4,
    inStock:true,
    fastDelivery:true,
    Appliances: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/612/612/ks4yz680/room-heater/q/x/f/ck-ms-moonstruck-original-imag5r78jzu4h67z.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "OnePlus Y1",
    deal: "Best Deals",
    price: "25499",
    category:"Appliances",
    discount:70,
    deliveryCh:50,
    ratings:4,
    inStock:true,
    fastDelivery:false,
    Appliances: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/312/312/kqidx8w0/television/o/h/9/43fa0a00-oneplus-original-imag4gy9perzvrdv.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "MI Y1",
    deal: "Best Deals",
    price: "26999",
    category:"Appliances",
    discount:70,
    deliveryCh:50,
    ratings:4,
    inStock:true,
    fastDelivery:true,
    Appliances: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/312/312/kr2e3680/television/9/l/o/l43m6-ei-mi-original-imag4xqrfhrewu2c.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Coffe Maker",
    deal: "Best Deals",
    price: "1599",
    category:"Appliances",
    discount:70,
    deliveryCh:50,
    ratings:4,
    inStock:false,
    fastDelivery:true,
    Appliances: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/612/612/kpydrbk0/coffee-maker/9/m/k/brewster-coffee-maker-14327-pigeon-original-imag42nzqvmbsp5s.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Moto Series",
    deal: "Best Deals",
    price: "78000",
    discount:2000,
    deliveryCh:100,
    ratings:3,
    inStock:false,
    fastDelivery:true,
    android: true,
    ios: false,
    image: 'https://rukminim2.flixcart.com/image/312/312/kn22m4w0/mobile/9/k/s/galaxy-f12-sm-f127glbiins-samsung-original-imagftmhhhvghq7w.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Samsung Series",
    deal: "Best Deals",
    price: "69000",
    category:"mobile",
    discount:2000,
    deliveryCh:79,
    ratings:3,
    inStock:false,
    fastDelivery:true,
    android: true,
    ios: false,
    image: 'https://rukminim2.flixcart.com/image/312/312/l0sgyvk0/mobile/k/x/c/-original-imagcg22czc3ggvw.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Apple series",
    deal: "Best Deals",
    price: "3000",
    category:"mobile",
    discount:60,
    deliveryCh:30,
    ratings:4,
    inStock:false,
    fastDelivery:true,
    ios: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/312/312/l0igvww0/mobile/n/h/4/-original-imagcahnwypwuaac.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Moto Series",
    deal: "Best Deals",
    price: "74000",
    category:"mobile",
    discount:2000,
    deliveryCh:60,
    ratings:2,
    inStock:true,
    fastDelivery:false,
    android: true,
    ios: false,
    image: 'https://rukminim2.flixcart.com/image/312/312/kn22m4w0/mobile/9/k/s/galaxy-f12-sm-f127glbiins-samsung-original-imagftmhhhvghq7w.jpeg?q=70'
  },
  {
    _id: uuid(),
    title: "Apple series",
    deal: "Best Deals",
    price: "39000",
    category:"mobile",
    discount:1400,
    deliveryCh:91,
    ratings:3,
    inStock:true,
    fastDelivery:true,
    ios: true,
    android: false,
    image: 'https://rukminim2.flixcart.com/image/312/312/l0sgyvk0/mobile/k/x/c/-original-imagcg22czc3ggvw.jpeg?q=70'
  }
];