export { highToLow } from '../filter-functions/high-to-low'
export {lowToHigh} from '../filter-functions/low-to-high'
export { inStock } from '../filter-functions/in-stock'
export { fastDelivery } from '../filter-functions/fast-delivery'
export { priceRange } from '../filter-functions/price-range'
export { rating } from '../filter-functions/rating'
export { categoryHandler } from '../filter-functions/category'